name: Build Android App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Set up Android SDK
        uses: android-actions/setup-android-sdk@v2

      - name: Install Gradle
        run: sudo apt-get install -y gradle

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Build Android App
        run: quasar build -m android --skip-pkg
